typography_spectrum: 0.8758756113238633
color:
  brandColors:
    - '#ffffff'
    - '#000000'
    - '#f9db59'
    - '#43dc32'
    - '#4ac5fa'
  brandStrength: 0.9436035263352096
  lightness: 0.4123407800216228
  saturation: 0.7183712103869766
  rhythmicContrast: 0.2980418913066387
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.043654987355694175
analytics:
  google: null
  facebook: null
  twitter: null
name: Triconium
cta:
  domain: null
  bucket: null
  version: null
favicon: null
description: Testing The Grid
purpose: []
